version: "2"

services:
  cadastro_falha:
    logging:
      driver: "json-file"
      options:
          max-size: "10m"  
    restart: always
    container_name: cadastro_falha
    build: 
      dockerfile: ../Cadastro_Falhas/Dockerfile
      context: ../Cadastro_Falhas/
    ports:
      - 8080:80
